### ISSUE TITLE
UnmappedClassError

### ISSUE THREAD

**Issue by tymiao1220** [OpenGeoscience/database_assetstore#41] opened 2017-08-02 19:59 UTC
Dear developers,

I am currently use your nice plugin to query informations from postgre database, it works nicely when dealing with single select query.

The problem is when I did iterate queries after one query as following:
/************code to explain*****************/
//First table query
girder.rest.restRequest({girderToken:token,type:'GET',path: "/file/"+seriesTable_id+"/database/select?limit=-1&sort=study_id&sortdir=-1&filters=%5B%7B%22and%22%3A%5B%5B%22series_date%22%2C%22gte%22%2C%222017-06-05%22%5D%2C%5B%22series_date%22%2C%22lte%22%2C%222017-06-06%22%5D%5D%7D%5D&format=json&wait=0&poll=10&initwait=0"})
//when it is done query all second tables with first table reference
        .done(function(resp){
            for(let i=0;i<resp.length;i++){
                let SeriesDescription=resp[i]["series_description"];
                let modality=resp[i]["modality"];
                let seriesId = resp[i]["series_uid"];
                let studyId = resp[i]["study_id"];
                let seriesPath = resp[i]["series_path"];
                girder.rest.restRequest({girderToken:token,type:'GET',path: "/file/"+studyTable_id+"/database/select?limit=-1&filters=%5B%22id%22%2C%22"+studyId+"%22%5D&format=json&wait=0&poll=10&initwait=0"})
                .done(function(resp2){//do something});
/**************end**************/

For some (happens at the very first query time, then if I redo same iterate query again it works like a charm) api query requests I got 500 server error:
/**************error*************/

GET http://ivg-boxx:8080/api/v1/file/5981db16f55fa30f145ec287/database/select?l…filters=%5B%22id%22%2C%2212654%22%5D&format=json&wait=0&poll=10&initwait=0 500 (Internal Server Error)

500 Internal Server Error {"message": "UnmappedClassError: UnmappedClassError(\"Class 'girder.plugins.database_assetstore.dbs.sqlalchemydb.Table' is not mapped\",)", "trace": [["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/api/rest.py", 561, "endpointDecorator", "val = fun(self, args, kwargs)"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/api/rest.py", 1109, "GET", "return self.handleRoute('GET', path, params)"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/api/rest.py", 884, "handleRoute", "val = handler(**kwargs)"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/api/rest.py", 1188, "wrapped", "return fn(self.ctx, *fargs, **fkwargs)"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/api/rest.py", 389, "wrapped", "return fun(*args, **kwargs)"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/plugins/database_assetstore/server/rest.py", 229, "databaseSelect", "file['_id'], dbinfo, queryparams)"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/plugins/database_assetstore/server/query.py", 407, "queryDatabase", "fields = conn.getFieldInfo()"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/plugins/database_assetstore/server/dbs/postgres_sqlalchemy.py", 122, "getFieldInfo", "super(PostgresSAConnector, self).getFieldInfo()"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/girder/plugins/database_assetstore/server/dbs/sqlalchemydb.py", 312, "getFieldInfo", "self.tableClass).iterate_properties:"], ["/home/miaot2/girder_env/local/lib/python2.7/site-packages/sqlalchemy/orm/base.py", 426, "class_mapper", "raise exc.UnmappedClassError(class_)"]], "type": "internal"}
/*****************end******************/

But when I check this particular case with single query no error at all.
Could you give me some help:-)
BTW nice plugin!

Best,

Adam

**Comment by manthey** [comment] 2017-08-02 20:32
I'm having reproducing this.

If I understand, you can make the first query to get the list of study_id, then it fails on the first query on the second table?

When we create a connection to the database, we have a class that maps the table columns to an ORM class.  The failure message is saying that mapping didn't happen, but I don't see how it can reach the code that is throwing an error without having generated that mapping.

**Comment by tymiao1220** [comment] 2017-08-03 13:46
@manthey Thank you for response! Here is the thing.
The first query works perfect, and it aim at getting seriesTable rows within specified date range. e.g.
series Table:
study_id | series_uid | update time|......
    50            2432          2010-07
    51             9912          2010-04
    .......

Then there is another table called studyTable, and I can use the study_id from first seriesTable to get the corresponding studyTable rows by iterating query all result row from first query
studyTable:
corresponding id | study name | ......
          50                      abdd             (will be selected)
          99                      dddfs           
          51                       adsfsf           (will be selected)

When I did iteration queries(second query) toward all first query result, some second queries(maybe not the first query(e.g. study_id==50 query), it could have on others, it is random) have that error at first iteration all queries time.
e.g. The first iteration I mention here means, I make a button to do all this queries, so when button is clicked  seriesTable query and studyTable iteration queries are implemented. 
If I redo this whole process(click button again), it is going right, no error pops up.

So the very interesting thing is if I did that error query separately, they all working good.
To me it is like iteration is too fast than request api skips (unable to catch) some query, just imagine:-)

If you have anything still not quit clear, let me know.
Again, truly appreciated!

Adam

**Comment by manthey** [comment] 2017-08-08 19:38
The only way I can get this error is when my Postgres database is unreachable (I deliberately stopped it).  I wonder if sometimes the connection gets a bad DNS value.  A retry loop around the connection might help resolve transient errors, but I'm not sure that it is the root cause of the problem.

**Comment by manthey** [comment] 2017-08-08 19:59
I've pushed a changed (PR #42).  Can you try it out and see if it resolves your issue?  If so, my guess is that you had a failed database connection once and that later it caused a problem.

**Comment by manthey** [comment] 2017-10-16 16:39
Fixed in PR #42.

**Closed by manthey** 2017-10-16 16:39 UTC
